// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "receipt",
            "region": "us-east-1"
        },
        {
            "tableName": "receiptUser",
            "region": "us-east-1"
        }
    ],
    "senderID":"336961904741",
    "aws_user_files_s3_bucket": "receiptmanagerstorage",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d690fb68-a670-4caf-aacf-ef935dcf9e4a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vj7r7vrTw",
    "aws_user_pools_web_client_id": "6ci9cmsokd4vgnm9c8no4uevac",
    "aws_cloud_logic_custom": [
        {
            "name": "api316d17f6",
            "endpoint": "https://1dwlpp8jak.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "receiptsAPI",
            "endpoint": "https://rj6hszkok1.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "S3CopyAPI",
            "endpoint": "https://j0tdibgm4m.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "moveReceiptsAPI",
            "endpoint": "https://2k9dg8fru2.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
        ,
        {
            "name": "userDetailsApi",
            "endpoint": "https://6qkeej3v58.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "notificationAPI",
            "endpoint": "https://qalazkdr95.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_mobile_analytics_app_id": "310e913ae3d34137933d12d8e5908116",
   
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
